# Generated by Django 4.2.7 on 2023-11-26 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        ('genero', '0001_initial'),
        ('editora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autores', models.ManyToManyField(to='autor.autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editora.editora')),
                ('generos', models.ManyToManyField(to='genero.genero')),
            ],
        ),
    ]
