# Generated by Django 4.2.7 on 2023-12-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='titulo',
            new_name='nome',
        ),
    ]
